// Mock-Daten für Entwicklung und Tests
import {Hotel, User, Booking, Room, RoomType, BookingStatus} from '../types/models';

export const mockUser: User = {
  id: '1',
  email: 'demo@booking.com',
  firstName: 'Max',
  lastName: 'Mustermann',
  phoneNumber: '+49 123 456789',
  profileImage: undefined,
};

export const mockHotels: Hotel[] = [
  {
    id: '1',
    name: 'Hotel Adlon Kempinski',
    description: 'Luxushotel am Brandenburger Tor mit spektakulärem Blick auf die Stadt.',
    address: 'Unter den Linden 77',
    city: 'Berlin',
    country: 'Deutschland',
    latitude: 52.5163,
    longitude: 13.3801,
    rating: 4.8,
    reviewCount: 1248,
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd',
    ],
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Parkplatz', 'Fitnessstudio'],
    pricePerNight: 350,
    currency: 'EUR',
  },
  {
    id: '2',
    name: 'The Westin Grand München',
    description: 'Elegantes Hotel im Herzen von München mit erstklassigem Service.',
    address: 'Arabellastraße 6',
    city: 'München',
    country: 'Deutschland',
    latitude: 48.1522,
    longitude: 11.6130,
    rating: 4.6,
    reviewCount: 892,
    images: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d',
    ],
    amenities: ['WiFi', 'Restaurant', 'Bar', 'Zimmerservice', 'Concierge'],
    pricePerNight: 220,
    currency: 'EUR',
  },
  {
    id: '3',
    name: 'Hotel Vier Jahreszeiten Hamburg',
    description: 'Traditionsreiches Luxushotel an der Binnenalster.',
    address: 'Neuer Jungfernstieg 9-14',
    city: 'Hamburg',
    country: 'Deutschland',
    latitude: 53.5547,
    longitude: 9.9928,
    rating: 4.9,
    reviewCount: 1567,
    images: [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4',
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa',
    ],
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Bar', 'Fitnessstudio', 'Parkplatz'],
    pricePerNight: 420,
    currency: 'EUR',
  },
  {
    id: '4',
    name: 'Motel One Köln',
    description: 'Modernes Budget-Hotel mit Design-Anspruch im Zentrum von Köln.',
    address: 'Cäcilienstraße 32',
    city: 'Köln',
    country: 'Deutschland',
    latitude: 50.9375,
    longitude: 6.9603,
    rating: 4.3,
    reviewCount: 543,
    images: [
      'https://images.unsplash.com/photo-1564501049412-61c2a3083791',
      'https://images.unsplash.com/photo-1587985064135-0366536eac42',
    ],
    amenities: ['WiFi', 'Bar', '24h-Rezeption'],
    pricePerNight: 85,
    currency: 'EUR',
  },
  {
    id: '5',
    name: 'Steigenberger Frankfurter Hof',
    description: 'Klassisches Grandhotel in bester Lage am Kaiserplatz.',
    address: 'Am Kaiserplatz',
    city: 'Frankfurt',
    country: 'Deutschland',
    latitude: 50.1109,
    longitude: 8.6821,
    rating: 4.7,
    reviewCount: 976,
    images: [
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd',
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39',
    ],
    amenities: ['WiFi', 'Restaurant', 'Bar', 'Spa', 'Zimmerservice', 'Parkplatz'],
    pricePerNight: 280,
    currency: 'EUR',
  },
];

export const mockRooms: Room[] = [
  {
    id: '1',
    hotelId: '1',
    name: 'Deluxe Zimmer',
    description: 'Geräumiges Zimmer mit Blick auf das Brandenburger Tor',
    type: RoomType.Deluxe,
    maxGuests: 2,
    pricePerNight: 350,
    images: ['https://images.unsplash.com/photo-1590490360182-c33d57733427'],
    amenities: ['King-Size-Bett', 'Minibar', 'Safe', 'Smart-TV'],
    available: true,
  },
  {
    id: '2',
    hotelId: '1',
    name: 'Suite',
    description: 'Luxuriöse Suite mit separatem Wohnbereich',
    type: RoomType.Suite,
    maxGuests: 4,
    pricePerNight: 650,
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b'],
    amenities: ['King-Size-Bett', 'Wohnzimmer', 'Minibar', 'Safe', 'Smart-TV', 'Espressomaschine'],
    available: true,
  },
];

export const mockBookings: Booking[] = [
  {
    id: '1',
    userId: '1',
    hotelId: '1',
    roomId: '1',
    checkIn: '2025-12-20',
    checkOut: '2025-12-23',
    guests: 2,
    totalPrice: 1050,
    currency: 'EUR',
    status: BookingStatus.Confirmed,
    createdAt: '2025-11-10T10:30:00Z',
    hotel: mockHotels[0],
    room: mockRooms[0],
  },
  {
    id: '2',
    userId: '1',
    hotelId: '3',
    roomId: '2',
    checkIn: '2026-01-15',
    checkOut: '2026-01-17',
    guests: 2,
    totalPrice: 840,
    currency: 'EUR',
    status: BookingStatus.Pending,
    createdAt: '2025-11-12T14:20:00Z',
    hotel: mockHotels[2],
  },
];
